### ISSUE TITLE
报错视频任务失败

### ISSUE THREAD

**Issue by NAILIANGCHI** [Samueli924/chaoxing_web#4]
Traceback (most recent call last):
  File "C:\Users\Desktop\chaoxing_web-main\chaoxing_web-main\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Desktop\chaoxing_web-main\chaoxing_web-main\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Desktop\chaoxing_web-main\chaoxing_web-main\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Desktop\chaoxing_web-main\chaoxing_web-main\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Desktop\chaoxing_web-main\chaoxing_web-main\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Desktop\chaoxing_web-main\chaoxing_web-main\web_listener.py", line 74, in start_learn
    ret = api.start_learn(usernm, courseid, speed)
  File "C:\Users\Desktop\chaoxing_web-main\chaoxing_web-main\api.py", line 798, in start_learn
    course.do_mp4(session, speed)
  File "C:\Users\Desktop\chaoxing_web-main\chaoxing_web-main\api.py", line 632, in do_mp4
    raise Exception("视频任务失败")
Exception: 视频任务失败

**Comment by NAILIANGCHI** [comment]
这是来自QQEmail的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
