### ISSUE TITLE
报错''视频任务失败''

### ISSUE THREAD

**Issue by MafuKun** [Samueli924/chaoxing_web#6]
Traceback (most recent call last):
  File "C:\Users\*\chaoxing_web\api.py", line 629, in do_mp4
    resp.json()
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
<title>403</title>
<style>
.main{height:255px;margin:0 auto;margin-top:15%;font-size:14px;color:#999; width: 350px;}
.font_top{padding-top:45px;display:inline;}
</style>
</head>
<body>
<div class="main">
<p class="font_top">>_< 很抱歉，您没有权限访问这个页面！  (403)</p>
<p style="font-size: 12px; color: #ddd;">60.26.3.158<br/>mooc-1726060061-mp49p</p>
</div>
</body>
</html>
: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\*\chaoxing_web\web_listener.py", line 74, in start_learn
    ret = api.start_learn(usernm, courseid, speed)
  File "C:\Users\*\chaoxing_web\api.py", line 798, in start_learn
    course.do_mp4(session, speed)
  File "C:\Users\*\chaoxing_web\api.py", line 632, in do_mp4
    raise Exception("视频任务失败")
Exception: 视频任务失败

**Comment by Samueli924** [comment]
请使用[Core核心库](https://github.com/Samueli924/chaoxing)  
后续内容将在核心库更新
